config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'cricbuzz/cricket'

  resources :appointments
  resources :registrations

  resources :patients

  resources :physicians

  resources :contacts

  resources :orders

  resources :customers

  resources :contactus

  get 'homes/myhome'

  
  get 'aboutus/about'

  

  

  get 'colleges/students'

  get 'colleges/principal1'

  get 'colleges/staff'

  root 'homes#myhome'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
	 belongs_to :physician
  belongs_to :patient
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	after_create :mails

	def mails
		UserMailer.registration_confirmation(self).deliver
		UserMailer.admin_mail(self).deliver
	end
end

app/models/contactu.rb
class Contactu < ActiveRecord::Base
	#validation: helpers + syntax -> metaprogramming
	#validates :name, :email, :address, :presence => true
	#validates :email, format: { with: /[a-z0-9._]+(@){1}[a-z0-9]+(\.){1}(com){1}/,
    #message: "Enter Correctly" }, uniqueness: true
    validates :cell, numericality: { only_integer: true }, :presence => true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :orders #@customer.orders.each
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :customer, :foreign_key => "customer_id"
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	has_many :appointments
  has_many :physicians, through: :appointments
end

app/models/physician.rb
class Physician < ActiveRecord::Base
	  has_many :appointments
  has_many :patients, through: :appointments
end

app/models/registration.rb
class Registration < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	layout "application", :only => [:myhome]
  def myhome
  end
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  before_action :set_physician, only: [:show, :edit, :update, :destroy]

  # GET /physicians
  # GET /physicians.json
  def index
    @physicians = Physician.all
  end

  # GET /physicians/1
  # GET /physicians/1.json
  def show
  end

  # GET /physicians/new
  def new
    @physician = Physician.new
  end

  # GET /physicians/1/edit
  def edit
  end

  # POST /physicians
  # POST /physicians.json
  def create
    @physician = Physician.new(physician_params)

    respond_to do |format|
      if @physician.save
        format.html { redirect_to @physician, notice: 'Physician was successfully created.' }
        format.json { render :show, status: :created, location: @physician }
      else
        format.html { render :new }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /physicians/1
  # PATCH/PUT /physicians/1.json
  def update
    respond_to do |format|
      if @physician.update(physician_params)
        format.html { redirect_to @physician, notice: 'Physician was successfully updated.' }
        format.json { render :show, status: :ok, location: @physician }
      else
        format.html { render :edit }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /physicians/1
  # DELETE /physicians/1.json
  def destroy
    @physician.destroy
    respond_to do |format|
      format.html { redirect_to physicians_url, notice: 'Physician was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_physician
      @physician = Physician.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def physician_params
      params.require(:physician).permit(:name, :age)
    end
end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/contactus_helper.rb
module ContactusHelper
	My_name = "m srinivas"
	def self.my_time
		@today = Time.new.strftime("%d-%m-%Y")
	end
end

app/helpers/cricbuzz_helper.rb
module CricbuzzHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/views/physicians/_form.html.erb
<%= form_for(@physician) do |f| %>
  <% if @physician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@physician.errors.count, "error") %> prohibited this physician from being saved:</h2>

      <ul>
      <% @physician.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/physicians/edit.html.erb
<h1>Editing physician</h1>

<%= render 'form' %>

<%= link_to 'Show', @physician %> |
<%= link_to 'Back', physicians_path %>

app/views/physicians/index.html.erb
<h1>Listing physicians</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @physicians.each do |physician| %>
      <tr>
        <td><%= physician.name %></td>
        <td><%= physician.age %></td>
        <td><%= link_to 'Show', physician %></td>
        <td><%= link_to 'Edit', edit_physician_path(physician) %></td>
        <td><%= link_to 'Destroy', physician, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Physician', new_physician_path %>

app/views/physicians/new.html.erb
<h1>New physician</h1>

<%= render 'form' %>

<%= link_to 'Back', physicians_path %>

app/views/physicians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @physician.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @physician.age %>
</p>

<%= link_to 'Edit', edit_physician_path(@physician) %> |
<%= link_to 'Back', physicians_path %>