config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'cricbuzz/cricket'

  resources :appointments
  resources :registrations

  resources :patients

  resources :physicians

  resources :contacts

  resources :orders

  resources :customers

  resources :contactus

  get 'homes/myhome'

  
  get 'aboutus/about'

  

  

  get 'colleges/students'

  get 'colleges/principal1'

  get 'colleges/staff'

  root 'homes#myhome'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
	 belongs_to :physician
  belongs_to :patient
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	after_create :mails

	def mails
		UserMailer.registration_confirmation(self).deliver
		UserMailer.admin_mail(self).deliver
	end
end

app/models/contactu.rb
class Contactu < ActiveRecord::Base
	#validation: helpers + syntax -> metaprogramming
	#validates :name, :email, :address, :presence => true
	#validates :email, format: { with: /[a-z0-9._]+(@){1}[a-z0-9]+(\.){1}(com){1}/,
    #message: "Enter Correctly" }, uniqueness: true
    validates :cell, numericality: { only_integer: true }, :presence => true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :orders #@customer.orders.each
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :customer, :foreign_key => "customer_id"
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	has_many :appointments
  has_many :physicians, through: :appointments
end

app/models/physician.rb
class Physician < ActiveRecord::Base
	  has_many :appointments
  has_many :patients, through: :appointments
end

app/models/registration.rb
class Registration < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/contactus_controller.rb
class ContactusController < ApplicationController
  before_action :set_contactu, only: [:show, :edit, :update, :destroy]

  # GET /contactus
  # GET /contactus.json
  def index
    @contactus = Contactu.all
  end

  # GET /contactus/1
  # GET /contactus/1.json
  def show
  end

  # GET /contactus/new
  def new
    @contactu = Contactu.new
  end

  # GET /contactus/1/edit
  def edit
  end

  # POST /contactus
  # POST /contactus.json
  def create
    @contactu = Contactu.new(contactu_params)

    respond_to do |format|
      if @contactu.save
        #UserMailer.registration_confirmation(@contactu).deliver
        format.html { redirect_to @contactu, notice: "successfully Saved" }
        format.json { render :show, status: :created, location: @contactu }
      else
        format.html { render :new }
        format.json { render json: @contactu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contactus/1
  # PATCH/PUT /contactus/1.json
  def update
    respond_to do |format|
      if @contactu.update(contactu_params)
        format.html { redirect_to @contactu, notice: 'Contactu was successfully updated.' }
        format.json { render :show, status: :ok, location: @contactu }
      else
        format.html { render :edit }
        format.json { render json: @contactu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contactus/1
  # DELETE /contactus/1.json
  def destroy
    @contactu.destroy
    respond_to do |format|
      format.html { redirect_to contactus_url, notice: 'Contactu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contactu
      @contactu = Contactu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contactu_params
      params.require(:contactu).permit(:name, :email, :cell, :address, :gender)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	layout "application", :only => [:myhome]
  def myhome
  end
end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/contactus_helper.rb
module ContactusHelper
	My_name = "m srinivas"
	def self.my_time
		@today = Time.new.strftime("%d-%m-%Y")
	end
end

app/helpers/cricbuzz_helper.rb
module CricbuzzHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/views/contactus/_form.html.erb
<%= form_for(@contactu) do |f| %>


  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :cell %><br>
    <%= f.text_field :cell %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contactus/edit.html.erb
<h1>Editing contactu</h1>

<%= render 'form' %>

<%= link_to 'Show', @contactu %> |
<%= link_to 'Back', contactus_path %>

app/views/contactus/index.html.erb
<h1>Listing contactus</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Cell</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contactus.each do |contactu| %>
      <tr>
        <td><%= contactu.name %></td>
        <td><%= contactu.email %></td>
        <td><%= contactu.cell %></td>
        <td><%= contactu.address %></td>
        <td><%= link_to 'Show', contactu %></td>
        <td><%= link_to 'Edit', edit_contactu_path(contactu) %></td>
        <td><%= link_to 'Destroy', contactu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contactu', new_contactu_path %>

app/views/contactus/new.html.erb
<h1>New contactu</h1>

<%= render 'form' %>

<%= link_to 'Back', contactus_path %>

app/views/contactus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contactu.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contactu.email %>
</p>

<p>
  <strong>Cell:</strong>
  <%= @contactu.cell %>
</p>

<p>
  <strong>Address:</strong>
  <%= @contactu.address %>
</p>

<%= link_to 'Edit', edit_contactu_path(@contactu) %> |
<%= link_to 'Back', contactus_path %>
<br/>
<%#= params[:controller] %><br/>
<%#= params[:action] %><br/>
<%#= params[:id] %><br/>
<%#= params[:name] %><br/>